$:
  vscode:
    - name: ddk-dev
      runner:
        cpus: 8
      docker:
        image: cnbcool/default-dev-env:latest
      git:
        enable: true
        submodules: false
      services:
        - vscode
        - docker
      stages:
        - name: env check
          script: |
            echo "CPU cores requested: 8"
            uname -a

main:
  web_trigger_ddk_dev:
    - name: ddk-dev
      runner:
        cpus: 4
      git:
        enable: true
        submodules: false
      services:
        - docker
      stages:
        - name: docker build
          script: |
            apt update && apt install -y jq make --no-install-recommends
            make -C docker ddk-dev-all PUSH=1 REG=${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}

  web_trigger_cnb_dev:
    - name: ddk-cnb-dev
      runner:
        cpus: 4
      git:
        enable: true
        submodules: false
        lfs: false
      services:
        - docker
      stages:
        - name: docker build
          script: |
            apt update && apt install -y jq make --no-install-recommends
            GIT_LFS_SKIP_SMUDGE=1 git submodule update --init --recursive --depth 1
            git lfs pull --include="prebuilts/clang/,prebuilts/rust/"
            make -C docker cnb-dev PUSH=1 REG=${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}
  
  web_trigger_builder:
    - name: ddk-builder
      runner:
        cpus: 4
      git:
        enable: true
        lfs: false
      services:
        - docker
      stages:
        - name: docker build
          script: |
            apt update && apt install -y jq make --no-install-recommends
            make -C docker builder PUSH=1 REG=${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}
