$:
  vscode:
    - name: ddk-dev-env
      runner:
        cpus: 64
      docker:
        image:
          name: ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}/ddk-cnb-dev:latest
      services:
        - vscode
        - docker
      stages:
        - name: env check
          script: |
            echo "CPU cores requested: 64"
            uname -a

main:
  web_trigger_cnb_dev:
    - name: ddk-cnb-dev
      runner:
        cpus: 4
      git:
        enable: true
        lfs: false
      services:
        - docker
      stages:
        - name: set docker tag
          script: echo -n "${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}/ddk-cnb-dev:latest"
          exports:
            info: IMAGE_TAG
        - name: docker build
          script: |
            git lfs pull --include="clang/"
            docker buildx build --push -t $IMAGE_TAG . -f .cnb/cnb-dev/Dockerfile
  web_trigger_builder:
    - name: ddk-builder
      runner:
        cpus: 4
      git:
        enable: true
        lfs: false
      services:
        - docker
      stages:
        - name: set docker tag
          script: echo -n "${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}/ddk-builder:latest"
          exports:
            info: IMAGE_TAG
        - name: build image
          script: |
            docker build -t $IMAGE_TAG . -f .cnb/Dockerfile
            docker push $IMAGE_TAG
  
  web_trigger_build_ddk:
    - name: ddk-matrix (manual)
      runner:
        cpus: 64
      docker:
        image:
          name: ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}/ddk-builder:latest
      git:
        enable: true
      stages:
        - name: env setup
          script: |
            set -eux
            echo "CPU cores available: $(nproc)"
            echo "Memory available:"
            free -h
            echo "Disk space available:"
            df -h
            pwd
            ls -al
            rsync -av --exclude .git ./ /opt/ddk/
            ls -al /opt/ddk
        
        - name: build
          jobs:
            android12-5.10:
              timeout: 4h
              script: |
                cd /opt/ddk
                source ./envsetup.sh
                setup_source android12-5.10 android12-5.10-2025-09_r1
                pushd src/android12-5.10
                rm -rf .git
                sed -i '/check_exports(mod);/s/^/\/\//' scripts/mod/modpost.c
                popd
                BUILD_PROC=9 build_kernel clang-r416183b android12-5.10
                tar --sort=name --mtime='UTC 2025-01-01' --owner=0 --group=0 --numeric-owner -C /opt/ddk/src -I 'zstd -T0' -cf "/opt/ddk/src.android12-5.10.tar.zst" android12-5.10
                tar --sort=name --mtime='UTC 2025-01-01' --owner=0 --group=0 --numeric-owner -C /opt/ddk/kdir -I 'zstd -T0' -cf "/opt/ddk/kdir.android12-5.10.tar.zst" android12-5.10

            android13-5.10:
              timeout: 4h
              script: |
                cd /opt/ddk
                source ./envsetup.sh
                setup_source android13-5.10 android13-5.10-2025-07_r1
                pushd src/android13-5.10
                rm -rf .git
                sed -i '/check_exports(mod);/s/^/\/\//' scripts/mod/modpost.c
                popd
                BUILD_PROC=9 build_kernel clang-r450784e android13-5.10
                tar --sort=name --mtime='UTC 2025-01-01' --owner=0 --group=0 --numeric-owner -C /opt/ddk/src -I 'zstd -T0' -cf "/opt/ddk/src.android13-5.10.tar.zst" android13-5.10
                tar --sort=name --mtime='UTC 2025-01-01' --owner=0 --group=0 --numeric-owner -C /opt/ddk/kdir -I 'zstd -T0' -cf "/opt/ddk/kdir.android13-5.10.tar.zst" android13-5.10

            android13-5.15:
              timeout: 4h
              script: |
                cd /opt/ddk
                source ./envsetup.sh
                setup_source android13-5.15 android13-5.15-2025-09_r2
                pushd src/android13-5.15
                rm -rf .git
                sed -i '/check_exports(mod);/s/^/\/\//' scripts/mod/modpost.c
                popd
                BUILD_PROC=9 build_kernel clang-r450784e android13-5.15
                tar --sort=name --mtime='UTC 2025-01-01' --owner=0 --group=0 --numeric-owner -C /opt/ddk/src -I 'zstd -T0' -cf "/opt/ddk/src.android13-5.15.tar.zst" android13-5.15
                tar --sort=name --mtime='UTC 2025-01-01' --owner=0 --group=0 --numeric-owner -C /opt/ddk/kdir -I 'zstd -T0' -cf "/opt/ddk/kdir.android13-5.15.tar.zst" android13-5.15

            android14-5.15:
              timeout: 4h
              script: |
                cd /opt/ddk
                source ./envsetup.sh
                setup_source android14-5.15 android14-5.15-2025-07_r1
                pushd src/android14-5.15
                rm -rf .git
                sed -i '/check_exports(mod);/s/^/\/\//' scripts/mod/modpost.c
                popd
                BUILD_PROC=9 build_kernel clang-r487747c android14-5.15
                tar --sort=name --mtime='UTC 2025-01-01' --owner=0 --group=0 --numeric-owner -C /opt/ddk/src -I 'zstd -T0' -cf "/opt/ddk/src.android14-5.15.tar.zst" android14-5.15
                tar --sort=name --mtime='UTC 2025-01-01' --owner=0 --group=0 --numeric-owner -C /opt/ddk/kdir -I 'zstd -T0' -cf "/opt/ddk/kdir.android14-5.15.tar.zst" android14-5.15

            android14-6.1:
              timeout: 4h
              script: |
                cd /opt/ddk
                source ./envsetup.sh
                setup_source android14-6.1 android14-6.1-2025-09_r4
                pushd src/android14-6.1
                rm -rf .git
                sed -i '/check_exports(mod);/s/^/\/\//' scripts/mod/modpost.c
                popd
                BUILD_PROC=9 build_kernel clang-r487747c android14-6.1
                tar --sort=name --mtime='UTC 2025-01-01' --owner=0 --group=0 --numeric-owner -C /opt/ddk/src -I 'zstd -T0' -cf "/opt/ddk/src.android14-6.1.tar.zst" android14-6.1
                tar --sort=name --mtime='UTC 2025-01-01' --owner=0 --group=0 --numeric-owner -C /opt/ddk/kdir -I 'zstd -T0' -cf "/opt/ddk/kdir.android14-6.1.tar.zst" android14-6.1

            android15-6.6:
              timeout: 4h
              script: |
                cd /opt/ddk
                source ./envsetup.sh
                setup_source android15-6.6 android15-6.6-2025-09_r5
                pushd src/android15-6.6
                rm -rf .git
                sed -i '/check_exports(mod);/s/^/\/\//' scripts/mod/modpost.c
                popd
                BUILD_PROC=9 build_kernel clang-r510928 android15-6.6
                tar --sort=name --mtime='UTC 2025-01-01' --owner=0 --group=0 --numeric-owner -C /opt/ddk/src -I 'zstd -T0' -cf "/opt/ddk/src.android15-6.6.tar.zst" android15-6.6
                tar --sort=name --mtime='UTC 2025-01-01' --owner=0 --group=0 --numeric-owner -C /opt/ddk/kdir -I 'zstd -T0' -cf "/opt/ddk/kdir.android15-6.6.tar.zst" android15-6.6

            android16-6.12:
              timeout: 4h
              script: |
                cd /opt/ddk
                source ./envsetup.sh
                setup_source android16-6.12 android16-6.12-2025-09_r2
                pushd src/android16-6.12
                rm -rf .git
                sed -i '/check_exports(mod);/s/^/\/\//' scripts/mod/modpost.c
                popd
                BUILD_PROC=9 build_kernel clang-r536225 android16-6.12
                tar --sort=name --mtime='UTC 2025-01-01' --owner=0 --group=0 --numeric-owner -C /opt/ddk/src -I 'zstd -T0' -cf "/opt/ddk/src.android16-6.12.tar.zst" android16-6.12
                tar --sort=name --mtime='UTC 2025-01-01' --owner=0 --group=0 --numeric-owner -C /opt/ddk/kdir -I 'zstd -T0' -cf "/opt/ddk/kdir.android16-6.12.tar.zst" android16-6.12

        - name: upload artifacts
          jobs:
            upload:
              image: cnbcool/attachments:latest
              settings:
                attachments:
                  - "/opt/ddk/src.android12-5.10.tar.zst"
                  - "/opt/ddk/kdir.android12-5.10.tar.zst"
                  - "/opt/ddk/src.android13-5.10.tar.zst"
                  - "/opt/ddk/kdir.android13-5.10.tar.zst"
                  - "/opt/ddk/src.android13-5.15.tar.zst"
                  - "/opt/ddk/kdir.android13-5.15.tar.zst"
                  - "/opt/ddk/src.android14-5.15.tar.zst"
                  - "/opt/ddk/kdir.android14-5.15.tar.zst"
                  - "/opt/ddk/src.android14-6.1.tar.zst"
                  - "/opt/ddk/kdir.android14-6.1.tar.zst"
                  - "/opt/ddk/src.android15-6.6.tar.zst"
                  - "/opt/ddk/kdir.android15-6.6.tar.zst"
                  - "/opt/ddk/src.android16-6.12.tar.zst"
                  - "/opt/ddk/kdir.android16-6.12.tar.zst"
