FROM ubuntu:24.04

RUN apt-get update && apt-get install -y \
    make \
    pahole \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/ddk

COPY clang/clang-r487747c ./clang/clang-r487747c
COPY src/android14-6.1 ./src/android14-6.1
COPY kdir/android14-6.1 ./kdir/android14-6.1

ENV DDK_ROOT=/opt/ddk \
    CROSS_COMPILE=aarch64-linux-gnu- \
    ARCH=arm64 \
    LLVM=1 \
    LLVM_IAS=1

ENV KERNEL_SRC=$DDK_ROOT/kdir/android14-6.1 \
    CLANG_PATH=$DDK_ROOT/clang/clang-r487747c/bin

ENV PATH=$CLANG_PATH:$PATH
    
CMD ["/bin/bash"]
ENTRYPOINT ["/bin/bash", "-C"]