FROM ubuntu:24.04

RUN apt-get update && apt-get install -y \
    make \
    pahole \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/ddk

COPY clang/clang-r536225 ./clang/clang-r536225
COPY src/android16-6.12 ./src/android16-6.12
COPY kdir/android16-6.12 ./kdir/android16-6.12

ENV DDK_ROOT=/opt/ddk \
    CROSS_COMPILE=aarch64-linux-gnu- \
    ARCH=arm64 \
    LLVM=1 \
    LLVM_IAS=1

ENV KERNEL_SRC=$DDK_ROOT/kdir/android16-6.12 \
    CLANG_PATH=$DDK_ROOT/clang/clang-r536225/bin

ENV PATH=$CLANG_PATH:$PATH
    
CMD ["/bin/bash"]
