FROM ubuntu:24.04

RUN apt-get update && apt-get install -y \
    make \
    pahole \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/ddk

COPY clang/clang-r510928 ./clang/clang-r510928
COPY src/android15-6.6 ./src/android15-6.6
COPY kdir/android15-6.6 ./kdir/android15-6.6

ENV DDK_ROOT=/opt/ddk \
    CROSS_COMPILE=aarch64-linux-gnu- \
    ARCH=arm64 \
    LLVM=1 \
    LLVM_IAS=1

ENV KERNEL_SRC=$DDK_ROOT/kdir/android15-6.6 \
    CLANG_PATH=$DDK_ROOT/clang/clang-r510928/bin

ENV PATH=$CLANG_PATH:$PATH
    
CMD ["/bin/bash"]
