FROM ubuntu:24.04

RUN apt-get update && apt-get install -y \
    make \
    pahole \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/ddk

COPY clang/clang-r450784e ./clang/clang-r450784e
COPY src/android13-5.15 ./src/android13-5.15
COPY kdir/android13-5.15 ./kdir/android13-5.15

ENV DDK_ROOT=/opt/ddk \
    CROSS_COMPILE=aarch64-linux-gnu- \
    ARCH=arm64 \
    LLVM=1 \
    LLVM_IAS=1

ENV KERNEL_SRC=$DDK_ROOT/kdir/android13-5.15 \
    CLANG_PATH=$DDK_ROOT/clang/clang-r450784e/bin

ENV PATH=$CLANG_PATH:$PATH
    
CMD ["/bin/bash"]
ENTRYPOINT ["/bin/bash", "-C"]