name: Build ddk with Nix

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - source_name: "android12-5.10"
            clang_name: "clang-r416183b"
            clang_branch_name: "master-kernel-build-2021"
          - source_name: "android13-5.10"
            clang_name: "clang-r450784e"
            clang_branch_name: "master-kernel-build-2022"
          - source_name: "android13-5.15"
            clang_name: "clang-r450784e"
            clang_branch_name: "master-kernel-build-2022"
          - source_name: "android14-5.15"
            clang_name: "clang-r487747c"
            clang_branch_name: "main-kernel-build-2023"
          - source_name: "android14-6.1"
            clang_name: "clang-r487747c"
            clang_branch_name: "main-kernel-build-2023"
          - source_name: "android15-6.6"
            clang_name: "clang-r510928"
            clang_branch_name: "main-kernel-build-2024"
          - source_name: "android16-6.12"
            clang_name: "clang-r536225"
            clang_branch_name: "main-kernel-2025"

    steps:
      - uses: actions/checkout@v4
      - uses: wimpysworld/nothing-but-nix@main
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Build ddk images (ddk and ddk-dev)
        run: |
          nix build .#${{ matrix.source_name }}
          nix build .#ddk-dev.$(echo "${{ matrix.source_name }}" | tr '-.' '__')

      - name: Push to GHCR (optional)
        if: ${{ secrets.GHCR_TOKEN != '' }}
        env:
          DEST_CREDS: ${{ github.actor }}:${{ secrets.GHCR_TOKEN }}
        run: |
          nix run .#${{ matrix.source_name }}.copyToRegistry -- --dest-creds "${DEST_CREDS}"
          nix run .#ddk-dev.$(echo "${{ matrix.source_name }}" | tr '-.' '__').copyToRegistry -- --dest-creds "${DEST_CREDS}"
